[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "goochess"
version = "0.1.0"
description = "Semantically written chess game with a GUI built using pygame."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "arcade",
]

[dependency-groups]
dev = [
    "pylint",
    "pyright",
    "pytest",
]

[tool.pyright]
typeCheckingMode = "basic"
venvPath = "."
venv = ".venv"

[tool.setuptools.packages.find]
where = ["src"]
include = ["goochess*"]
namespaces = false

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pylint.main]
source-roots = [
    "src",
]
ignored-modules = [
    "pygame",
]

[tool.pylint.format]
indent-string = "\t"
max-line-length = 132

[tool.pylint.messages_control]
disable = [
    "C",
    "R",
    "W",
]
