[project]
name = "goochess"
version = "0.1.0"
description = "Behavior-rich chess engine with an optional Pygame frontend."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[project.optional-dependencies]
app = [
    "pygame",
]

[dependency-groups]
dev = [
    "pylint",
    "pyright",
    "pytest",
]

[tool.pylint.main]
ignored-modules = [
    "pygame",
]
source-roots = [
    ".",
]

[tool.pylint.format]
indent-string = "\t"
max-line-length = 132

[tool.pylint.messages_control]
disable = [
    "C",
    "R",
    "W",
]

[tool.pytest.ini_options]
pythonpath = [
    ".",
]
testpaths = [
    "tests",
]
