[project]
name = "goochess"
version = "0.1.0"
description = "Semantically written chess game with a GUI built using pygame."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pygame",
]

[dependency-groups]
dev = [
    "pylint",
    "pyright",
    "pytest",
]

[tool.pylint.main]
ignored-modules = [
    "pygame",
]

[tool.pylint.format]
indent-string = "\t"
max-line-length = 132

[tool.pylint.messages_control]
disable = [
    "C",
    "R",
    "W",
]
